### ISSUE TITLE
ValueError: cannot reshape array of size 657072 into shape (624,468)

### ISSUE THREAD

**Issue by huawei80** [bubbliiiing/mask-rcnn-tf2#12]
博主你好，我在运行train.py的时候，咋快要运行完第一个epoch时，遇到了下面问题，希望您帮我看看。

 masks = masks.reshape((-1, height, width))
ValueError: cannot reshape array of size 657072 into shape (624,468)

![image](https://user-images.githubusercontent.com/63716910/187157936-e87c8815-6a1b-4fce-a6d9-86271f29a8bc.png)

**Comment by bubbliiiing** [comment]
是不是有一个mask和img不对应呀

**Comment by huawei80** [comment]
那博主这要怎么办呢？现在试了很多方法也改不正确，是从数据集输入的问题吗？？我用您说的Lableme转成coco格式的就可以跑通，但是用自己deepfashion2数据集转化成coco格式，就出现了这样的问题
