### ISSUE TITLE
训练coco数据集出现报错

### ISSUE THREAD

**Issue by Echo-gh** [bubbliiiing/mask-rcnn-tf2#21]
博主你好，我下载了你的程序以及coco训练集，运行train.py的过程中出现了报错，报错内容如下所示：
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[1] = 130486 is not in [0, 65472)
         [[node mask_rcnn/ROI/GatherV2_12 (defined at /home/***/tf2/mask-rcnn-tf2/nets/layers.py:125) ]] [Op:__inference_train_function_54052]

Errors may have originated from an input operation.
Input Source operations connected to node mask_rcnn/ROI/GatherV2_12:
 mask_rcnn/ROI/strided_slice_27 (defined at /home/***/tf2/mask-rcnn-tf2/nets/layers.py:12)

Function call stack:
train_function

2022-11-21 21:34:09.373886: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]

运行环境是WSL2 Ubuntu-22.04，各个程序版本如下所示：
scipy==1.4.1
numpy==1.22.3
matplotlib==3.2.2
opencv_python==4.2.0.34
tensorflow_gpu==2.4.0
tqdm==4.46.1
Pillow==8.2.0
h5py==2.10.0

我在网上没有找到相关的报错原因，所以想咨询一下博主是否知道报错的原因呢？谢谢。

**Comment by bubbliiiing** [comment]
cuda和cudnn是？

**Comment by Echo-gh** [comment]
> cuda和cudnn是？
谢谢回复。
cuda是11.8  cudnn是8.6。

**Comment by Echo-gh** [comment]
> cuda和cudnn是？

你好，我今天又试着更改了一下环境：

运行环境是WSL2 Ubuntu-18.04，各个程序版本如下所示：
scipy==1.4.1
numpy==1.19.2
matplotlib==3.2.1
opencv_python==4.2.0.34
tensorflow_gpu==2.4.0
tqdm==4.46.1
Pillow==8.2.0
h5py==2.10.0

由于我是在win10 WSL2环境下进行实验的，CUDA11.0没有wsl版本，所以我选择了CUDA11.2、CUDNN8.1，程序仍然会报上述类似的错误，不知道是怎么回事。

**Comment by bubbliiiing** [comment]
11.2貌似不适合2.4，需要改改

**Comment by Echo-gh** [comment]
> 11.2貌似不适合2.4，需要改改

不好意思 前几天在封控没看消息
请问具体要该哪里呀？方便给出一些指导吗？

**Comment by Echo-gh** [comment]
> 就是不适合tensorflow2.4 CUDA11.2这个得参考一下tensorflow官方，应该有些

嗯 官方推荐tf2.5或2.6  我换成这两个试一下吧
谢谢回复哈

**Comment by Echo-gh** [comment]
感谢博主 更换为tf2.5之后跑通了 
但是有个问题 目前的显存占用率维持在80%左右，怎么提高显存的占用率呢？是增加batch_size的大小吗？
