### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[1] = 129181 is not in [0, 65472)+Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.

### ISSUE THREAD

**Issue by daixin0609** [bubbliiiing/mask-rcnn-tf2#26]
博主您好，我使用的版本是 cpu，tf2.2.0，使用shape数据集未更改其他参数，在运行train文件的epoch1时有如下报错，看了以往的问题与解决办法，尝试过换tf2.2-gpu或tf2.6-gpu，但均出现如图错误。请问应该如何修改？感谢您的回复！
![image](https://user-images.githubusercontent.com/124659246/217542442-221acb89-97c5-4959-b542-3ec03b62a549.png)
![image](https://user-images.githubusercontent.com/124659246/217542490-a23346a6-5dd1-4a88-b549-948508e859d2.png)
![image](https://user-images.githubusercontent.com/124659246/217544796-19d61807-bd4d-4cc5-840a-d4267e8ee9c7.png)
![image](https://user-images.githubusercontent.com/124659246/217544890-1a69fd37-2ea9-462b-b1ee-81492a8c464d.png)

**Comment by bubbliiiing** [comment]
这个问题是cuda版本不对导致的，你是什么cuda版本那~

**Comment by daixin0609** [comment]
> 

谢谢博主的回复！！我的电脑：python3.6、没有gpu，tf2.2报错，试了keras版本的也是这个错误，很奇怪，下面是keras版的报错。
![image](https://user-images.githubusercontent.com/124659246/217731600-2493587f-fbbb-4355-83c2-9842dca082d7.png)

试了同学的电脑：pyhon3.6、在cmd里用nvidia-smi查询的cuda版本是11.7，但是之前安装pytorch的时候安装了11.1的cuda+11.2的cudnn。用tf2.2/tf2.4/tf2.6都是一样的错误，哭了

**Comment by daixin0609** [comment]
补充一下：在tf2.4虚拟环境下ncc-V显示cuda11.1，按理说11.1和2.4是对应的

**Comment by CUIYINGHAO-INU** [comment]
> 补充一下：在tf2.4虚拟环境下ncc-V显示cuda11.1，按理说11.1和2.4是对应的

CUDA的版本可以通过路径：

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\你的cuda版本文件

不知道是不是你cudnn的版本没安装对。可以看看英伟达官网里找到cudnn xx版本 for CUDA 11.1，然后需要把cudnn文件里的文件夹复制粘贴到CUDA的对应文件夹里。

另外，我之前配置过cuda11.1 & cudnn 8.3.1 在3090GPU，tensorflow 2.5.0运行成功过，希望对你有帮助

**Comment by daixin0609** [comment]
好的，谢谢博主的回复，我有空再试一下！
