### ISSUE TITLE
报错“数据集过小，无法进行训练，请扩充数据集”。

### ISSUE THREAD

**Issue by qa1511** [bubbliiiing/mask-rcnn-tf2#36]
B导您好，我使用的是您shape数据集
默认    
trainval_percent    = 0.9
train_percent       = 0.9
提示
数据集过小，无法进行训练，请扩充数据集，然后再CSDN上面看到也有人问了这个问题，您回复了“划分没划分好，所以显示不足”
之后我将其更改为
trainval_percent    = 0.7
train_percent       = 0.7
还是提示数据集过小，无法进行训练，请扩充数据集，请问是什么问题呢，需要划分多少才合理呢

**Comment by Knee23** [comment]
同问，我的数据集有4000+，batch_size设为1，都还会提示数据集过小，是怎么回事呢？
